DefaultContentLanguage = "en"
author = "Kristina Simakova"
baseURL = "https://ar-test-moo.netlify.app"
copyright = "Copyright © 2020; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Learn AR Online"
[menu]
main = []
[params]
description = "Learn AR by doing project - based tutorials"
facebook = "https://facebook.com"
github = "https://github.com/"
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
